version: '3'
services:
  anagrammy-api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5884:5884
  postgresdb:
    image: postgres:14
    ports:
      - "5922:5432"
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/10-init.sql
      - ./scripts/anagrammy.sql:/docker-entrypoint-initdb.d/20-anagrammy.sql

    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081

volumes:
  postgresdb_data: {}
